# Generated by Django 3.0 on 2020-10-17 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='vessels.Vessel')),
            ],
        ),
    ]
