# Generated by Django 3.0 on 2020-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
